name: getimg
on:
  schedule: [{cron: "0 8 * * *"}]
  push: {branches: ["wf"]}
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-18.04
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: du5
          template: classic
          base: header, repositories, metadata
          config_timezone: Asia/Shanghai
          plugin_activity: yes
          plugin_activity_days: 100
          plugin_activity_filter: all
          plugin_activity_limit: 5
          plugin_languages: yes
          plugin_languages_ignored: TSQL,JavaScript,CSS,HTML,Smarty,SCSS,Shell,Blade,XSLT,CMake,Roff,Makefile,Batchfile
          plugin_pagespeed: yes
          plugin_pagespeed_detailed: yes
          plugin_pagespeed_url: https://gtary.com/
          plugin_pagespeed_token: ${{ secrets.PAGESPEED_TOKEN }}
