name: gimg
on:  
  push:
    branches: 
      - wf
  schedule:
    - cron: '*/15 * * * *'
jobs:
  github-metrics:
    runs-on: ubuntu-18.04
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          user: du5
          template: classic
          base: repositories, metadata
          config_animated: yes
          config_timezone: Asia/Shanghai
          plugin_activity: yes
          plugin_activity_days: 90
          plugin_activity_filter: all
          plugin_activity_limit: 10
          plugin_languages: yes
